"ui.background" = { bg = "base00" }
"ui.menu" = { fg = "base05", bg = "base01" }
"ui.menu.selected" = { fg = "base01", bg = "base04" }
"ui.popup" = { bg = "base01" }
"ui.window" = { bg = "base01" }
"ui.linenr" = { fg = "base03", bg = "base01", modifiers = ["bold"] }
"ui.linenr.selected" = { fg = "base04", bg = "base01", modifiers = ["bold"] }
"ui.selection" = { bg = "base02" }
"comment" = { fg = "base03", modifiers = ["italic", "dimed"] }
"ui.statusline" = { fg = "base04", bg = "base01" }
"ui.cursor" = { fg = "base04", modifiers = ["reversed"] }
"ui.cursor.primary" = { fg = "base05", modifiers = ["reversed"] }
"ui.virtual.whitespace" = "base03"
"ui.virtual.jump-label" = { fg = "blue", modifiers = ["bold", "underlined"] }
"ui.virtual.ruler" = { bg = "base01" }

"ui.text" = "base05"
"operator" = { fg = "base05", modifiers = ["bold"] }
"ui.text.focus" = "base05"
"variable" = "base08"
"constant.numeric" = { fg = "base09", modifiers = ["bold"] }
"constant" = { fg = "base09", modifiers = ["bold"] }
"attribute" = "base09"
"type" = { fg = "base0A", modifiers = ["bold", "underlined"] }
"ui.cursor.match" = { fg = "base0A", modifiers = ["underlined"] }
"string"  = { fg = "base0B", modifiers = ["italic"] }
"variable.other.member" = "base0B"
"constant.character.escape" = "base0C"
"function" = "base0D"
"constructor" = { fg =  "base0D", modifiers = ["bold", "underlined"] }
"special" = "base0D"
"keyword" = { fg = "base0E", modifiers = ["bold"] }
"label" = "base0E"
"namespace" = "base0E"
"ui.help" = { fg = "base06", bg = "base01" }

"markup.heading" = "base0D"
"markup.list" = "base08"
"markup.bold" = { fg = "base0A", modifiers = ["bold"] }
"markup.italic" = { fg = "base0E", modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url" = { fg = "base09", modifiers = ["underlined"] }
"markup.link.text" = "base08"
"markup.quote" = "base0C"
"markup.raw" = "base0B"

"diff.plus" = "base0B"
"diff.delta" = "base09"
"diff.minus" = "base08"

"diagnostic" = { modifiers = ["underlined"] }
"ui.gutter" = { bg = "base01" }
"info" = "base0D"
"hint" = "base03"
"debug" = "base03"
"warning" = "base09"
"error" = "base08"

"ui.bufferline" = { fg = "base04", bg = "base01" }
"ui.bufferline.active" = { fg = "base07", bg = "base00" }

[palette]
base00 = "#ffffff" # Default Background
base01 = "#ffffff" # Lighter Background (Used for status bars, line number and folding marks)
base02 = "#ababab" # Selection Background
base03 = "#888888" # Comments, Invisibles, Line Highlighting
base04 = "#000000" # Dark Foreground (Used for status bars)
base05 = "#000000" # Default Foreground, Caret, Delimiters, Operators
base06 = "#000000" # Light Foreground (Not often used)
base07 = "#ffffff" # Light Background (Not often used)
base08 = "#000000" # Variables, XML Tags, Markup Link Text, Markup Lists, Diff Deleted
base09 = "#000000" # Integers, Boolean, Constants, XML Attributes, Markup Link Url
base0A = "#000000" # Classes, Markup Bold, Search Text Background
base0B = "#000000" # Strings, Inherited Class, Markup Code, Diff Inserted
base0C = "#000000" # Support, Regular Expressions, Escape Characters, Markup Quotes
base0D = "#000000" # Functions, Methods, Attribute IDs, Headings
base0E = "#000000" # Keywords, Storage, Selector, Markup Italic, Diff Changed
base0F = "#000000" # Deprecated, Opening/Closing Embedded Language Tags, e.g. <?php ?>

