"ui.linenr.selected" = { modifiers = ["reversed"] }
"ui.selection" = { bg = "gray0" }
"ui.cursor" = { modifiers = ["reversed"] }
"ui.cursor.match" = { underline = { style = "line" } }
"ui.cursor.primary" = { modifiers = ["reversed"] }

"ui.text.focus" = { underline = { style = "line" } }
"ui.virtual.jump-label" = { fg = "magenta", modifiers = ["bold"] }
"ui.bufferline.active" = { modifiers = ["reversed"] }

"annotation" = { fg = "gray", modifiers = ["italic"] }

"attribute" = { fg = "cyan", modifiers = ["italic"] }

"comment" = { fg = "gray", modifiers = ["italic"] }

"constant" = { fg = "magenta" }

"constructor" = { fg = "magenta" }

"definition" = { underline = { color = "cyan" } }

"diagnostic" = { modifiers = ["crossed_out"] }

"variable" = {  }

"error" = { fg = "red" }
"hint" = { fg = "blue" }
"info" = { fg = "cyan" }
"warning" = { fg = "yellow" }

"diff.delta" = { fg = "yellow" }
"diff.minus" = { fg = "red" }
"diff.plus" = { fg = "green" }

"function" = { fg = "green" }

"keyword" = { fg = "red" }

"label" = { fg = "red" }

"markup.bold" = { modifiers = ["bold"] }
"markup.heading" = "cyan"
"markup.italic" = { modifiers = ["italic"] }
"markup.link.text" = "red"
"markup.link.url" = { fg = "blue", modifiers = ["underlined"] }
"markup.raw" = "red"
"markup.strikethrough" = { modifiers = ["crossed_out"] }

"module" = { fg = "cyan" }

"namespace" = {  }

"operator" = { fg = "magenta" }

"punctuation" = { fg = "orange1" }

"special" = { fg = "magenta" }

"string" = { fg = "green" }

"tag" = { fg = "cyan" }

"tabstop" = { fg = "gray" }

"type" = { fg = "blue", modifiers = ["bold"], underline = { style = "line" } }

[palette]
gray0 = "#ababab"