theme = "ink"

[editor]
true-color = true
bufferline = "multiple"
insert-final-newline = false

[editor.soft-wrap]
enable = true
wrap-indicator = ""

[keys.normal]
C-s = ":update"
C-c = ":clipboard-yank"
C-v = ":clipboard-paste-before"
backspace = "delete_char_backward"
A-backspace = "delete_word_backward"
del = "delete_selection_noyank"
A-del = "delete_selection"
r = "replace_with_yanked"
R = "replace"
"(" = ":buffer-previous"
")" = ":buffer-next"
"_" = ":buffer-close"
minus = "trim_selections"
J = "page_cursor_half_down"
K = "page_cursor_half_up"

[keys.insert]
C-s = "normal_mode"
ret = ["commit_undo_checkpoint", "insert_newline"]
