theme = "ink"

[editor]
true-color = true
bufferline = "multiple"

[editor.soft-wrap]
enable = true
wrap-indicator = ""

[keys.normal]
C-s = ":update"
C-c = ":clipboard-yank"
C-v = ":clipboard-paste-before"
backspace = "delete_char_backward"
A-backspace = "delete_word_backward"
del = "delete_selection_noyank"
A-del = "delete_selection"
r = "replace_with_yanked"
R = "replace"
"_" = ":buffer-close"
minus = "trim_selections"
J = "page_cursor_half_down"
A-j = "page_down"
K = "page_cursor_half_up"
A-k = "page_up"

[keys.insert]
C-s = "normal_mode"
C-c = ":clipboard-yank"
C-v = ":clipboard-paste-before"
A-backspace = "delete_word_backward"
ret = ["commit_undo_checkpoint", "insert_newline"]
